<?php
/**
 * @author: jinnoflife <git@jinnoflife.com>
 * @package: JolMediaCollector
 */

namespace JolMediaCollector;

use Shopware\Components\Plugin;
use Shopware\Components\Plugin\Context\ActivateContext;
use Shopware\Components\Plugin\Context\DeactivateContext;
use Shopware\Components\Plugin\Context\InstallContext;
use Shopware\Components\Plugin\Context\UninstallContext;

/**
 * Class JolMediaCollector
 */
class JolMediaCollector extends Plugin
{
    /**
     * @param InstallContext $context
     */
    public function install(InstallContext $context)
    {
        parent::install($context); // TODO: Change the autogenerated stub
    }

    /**
     * @param ActivateContext $context
     */
    public function activate(ActivateContext $context)
    {
        parent::activate($context); // TODO: Change the autogenerated stub
    }

    /**
     * @param DeactivateContext $context
     */
    public function deactivate(DeactivateContext $context)
    {
        parent::deactivate($context); // TODO: Change the autogenerated stub
    }

    /**
     * @param UninstallContext $context
     */
    public function uninstall(UninstallContext $context)
    {
        parent::uninstall($context); // TODO: Change the autogenerated stub
    }
}
